# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d160f830f8fef9650b684657ab76ea6a10d3ea1d5cd56fb0501768d4517f248a7032084a92af75b9fa5f96cacd1491369636d60523a98c35442c36396a4e5c2b

test:
  secret_key_base: 0c38d8bd9c9ca2570dec4ec70218494452ecc5ec68a3cd04fba950f48e3cd0b10d11304c79bad8e5a324687d67190911c4627b0f5538dc46ef6dbfef41cf4943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
